name: Location Deployment

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install SSH key
        run: echo "$SSH_PRIVATE_KEY" > deploy_key && chmod 600 deploy_key

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-scripts --no-progress --no-suggest

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Set permissions
        run: chmod -R 755 storage bootstrap/cache

      - name: Deploy to cPanel
        uses: AppleEducate/cpanel-deploy@v2
        with:
          cpanel-username: ${{ secrets.CPANEL_USERNAME }}
          cpanel-password: ${{ secrets.CPANEL_PASSWORD }}
          cpanel-host: ahmadakorede.com.ng
          cpanel-domain: location.ahmadakorede.com.ng
          app-directory: public_html/location

